version: '3'
services:
  db:
    image: postgres:15
    networks:
      - civviebot_db
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data/
      # Pre-loading tables as CREATE IF NOT EXISTS is susceptible to race
      # conditions that could be triggered by spinning up the API and bot at
      # the same time.
      - database/sql/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 10
  api:
    image: civviebot
    command: ['python', '-m', 'gunicorn', '-b', '0.0.0.0:3002', 'civviebot_api:civviebot_api']
    expose:
      - 80
    ports:
      - 80:3002
    networks:
      - civviebot_db
    env_file: .env
    depends_on:
      - db
  bot:
    image: civviebot
    command: ['python', 'civviebot.py']
    networks:
      - civviebot_db
    env_file: .env
    depends_on:
      - db
networks:
  civviebot_db:
    external: false
volumes:
  db_data:
