services:
  mysql:
    image: mysql:8
    secrets:
      - db_root_password
      - db_name
      - db_user
      - db_password
    networks:
      - db_network
  civviebot:
    image: civviebot
    build: .
    environment:
      - LOGGING_CONFIG=./logging.yml
    volumes:
      - source: ${LOGGING_CONFIG}
        type: volume
        target: /logging.yml
    env_file: .env
    depends_on:
      - mysql
  civviebot_api:
    image: civviebot
    ports:
      - "80:${CIVVIEBOT_PORT}"
    environment:
      - CIVVIEBOT_HOST="0.0.0.0"
      - CIVVIEBOT_PORT=3002
    depends_on:
      - civviebot
secrets:
  db_root_password:
networks:
  db_network: