services:
  civviebot:
    image: civviebot
    ports:
      - "80:3002"
    build: .
    environment:
      - SQLITE_DATABASE=./database.sqlite
      - LOGGING_CONFIG=./logging.yml
    volumes:
      - source: ${SQLITE_DATABASE}
        type: volume
        target: /database.sqlite
      - source: ${LOGGING_CONFIG}
        type: volume
        target: /logging.yml
    env_file: .env