apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - .kubernetes/civviebot-civviebot-db-networkpolicy.yaml
  - .kubernetes/env-configmap.yaml
  - .kubernetes/api/api-deployment.yaml
  - .kubernetes/api/api-service.yaml
  - .kubernetes/bot/bot-deployment.yaml
  - .kubernetes/db/db-deployment.yaml
  - .kubernetes/db/db-service.yaml
  - .kubernetes/db/db-data-persistentvolumeclaim.yaml
  - .kubernetes/db/db-claim1-persistentvolumeclaim.yaml
commonLabels:
  app: civviebot