version: 1
formatters:
  base:
    format: "[{asctime} ({filename}:{lineno}:{funcName}) {levelname}]: {message}"
    style: '{'
handlers:
  console:
    class: logging.StreamHandler
    formatter: base
    level: DEBUG
    stream: ext://sys.stdout
  logrotate:
    class: logging.handlers.RotatingFileHandler
    formatter: base
    level: DEBUG
    mode: a
    encoding: utf-8
    filename: civviebot.log
    maxBytes: 5000
loggers:
  discord:
    level: INFO
    handlers: [console]
  civviebot:
    level: INFO
    handlers: [console]