# Copy this file and save it as 'config.yml' in civviebot's root folder, filling
# out any missing settings. Alternatively, you can copy this file anywhere that
# civviebot can see, name it whatever you'd like, and set the CIVVIEBOT_CONFIG
# environment variable to point to the config file.
#
# Paths to various files needed by CivvieBot (relative to the root folder of
# civviebot, or to a folder passed in using the CIVVIEBOT_PATH environment
# variable):
#
paths:
  # Either an existing database, or a new one that will be created if it doesn't
  # exist
  database: database.sqlite
  # Logging configuration, for use with the python logging module in YAML.
  logging: logging.yml
#
# The slash command prefix CivvieBot commands will use; e.g., c6 to create
# commands grouped like /c6url and /c6player
command_prefix: c6
#
# Configuration defaults (these options can be changed for individual URLs and
# games, but newly-minted URLs will present these values as defaults):
#
# The number of turns that must pass in a game before notification messages are
# actually sent
min_turns: 10
# The maximum number of seconds that should elapse between turns before
# re-pinging folks; 604800 seconds equates to one week
stale_notification_length: 604800
#
# Notification and cleanup settings:
#
# How frequent the bot should check the database for new notifications to be
# sent, in seconds
notification_interval: 5.0
# The maximum number of each to send out when the bot checks the database for
# new turns and re-pings
notification_limit: 100
# How frequent the bot should run cleanup on the database, in seconds; 86400.0
# seconds equates to 24 hours
cleanup_interval: 86400.0
# How many of each game, player, and webhook URL should be deleted every
# cleanup_interval
cleanup_limit: 1000
# How old, in seconds, the last turn notification should be before a game is
# considered stale and should be cleaned up; 2592000 seconds equates to 30 days
stale_game_length: 2592000
#
# Discord and bot settings:
#
# Your Discord bot's client ID
discord_client_id:
# Your Discord bot's client secret
discord_client_secret:
# Your Discord API token
discord_token:
# A debug guild to use; leave this empty if not debugging
debug_guild:
#
# API settings:
#
# The host this app will respond to requests at; this is only really used for
# sending messages containing a full webhook URL
host: localhost
# The port that the API for this app should respond on
port: 3002