# Webhook creds.
webhook_url: CHANGE_ME
# For now; seems the simplest way to translate Steam usernames to Discord.
user_map:
  steam_user_a: 12345
  steam_user_b: 67890
# Civ VI sends really dumb JSON containing:
# - 'value1' as the title that was given to the game
# - 'value2' as the name of the person whose turn is up
# - 'value3' as the turn number
# They can be used here as replacement values.
phrases:
  - "It's turn number {value3} for {value2} in {value1}."
  - "{value2} is up in {value1} for turn {value3}."
  - "{value2}, it's turn number {value3} for you in {value1}."
# This would be the Flask DEBUG flag
debug_mode: false
# Messages will not be sent for turns lower than this number.
minimum_turn: 20
# Override some of the basic config for the messages being sent.
webhook_username: false
webhook_avatar_url: false
