apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: CIVVIEBOT_DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_DIALECT
                  name: env
            - name: CIVVIEBOT_DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_DRIVER
                  name: env
            - name: CIVVIEBOT_DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_URL_DATABASE
                  name: env
            - name: CIVVIEBOT_DB_URL_HOST
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_URL_HOST
                  name: env
            - name: CIVVIEBOT_DB_URL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_URL_PASSWORD
                  name: env
            - name: CIVVIEBOT_DB_URL_PORT
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_URL_PORT
                  name: env
            - name: CIVVIEBOT_DB_URL_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_URL_USERNAME
                  name: env
            - name: DISCORD_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_CLIENT_ID
                  name: env
            - name: DISCORD_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_TOKEN
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
          image: postgres:15
          livenessProbe:
            exec:
              command:
                - pg_isready -U ${POSTGRES_USER}
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: db
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: init-script
              subPath: tables.sql
            - mountPath: /var/lib/postgresql
              name: db-data-claim
          resources: {}
      volumes:
        - name: db-data-claim
          persistentVolumeClaim:
            claimName: db-data-claim
        - name: init-script
          configMap:
            name: db-configmap
