apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-claim
  labels:
    app: db
spec:
  storageClassName: civviebot-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi