apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/civviebot-civviebot-db: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: CIVVIEBOT_DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_DIALECT
                  name: env
            - name: CIVVIEBOT_DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_DRIVER
                  name: env
            - name: CIVVIEBOT_DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_URL_DATABASE
                  name: env
            - name: CIVVIEBOT_DB_URL_HOST
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_URL_HOST
                  name: env
            - name: CIVVIEBOT_DB_URL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_URL_PASSWORD
                  name: env
            - name: CIVVIEBOT_DB_URL_PORT
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_URL_PORT
                  name: env
            - name: CIVVIEBOT_DB_URL_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: CIVVIEBOT_DB_URL_USERNAME
                  name: env
            - name: DISCORD_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_CLIENT_ID
                  name: env
            - name: DISCORD_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_TOKEN
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
          image: postgres:15
          livenessProbe:
            exec:
              command:
                - pg_isready -U ${POSTGRES_USER}
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/tables.sql
              name: db-claim1
      restartPolicy: Always
      volumes:
        - name: db-claim1
          persistentVolumeClaim:
            claimName: db-claim1
status: {}
