apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-claim
  labels:
    app: db
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi