apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
spec:
  storageClassName: standard-rwo
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    readOnly: false
    fsType: ext4
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/smart-processor-373519/zones/northamerica-northeast1-a/disks/civviebot-disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
              - db