apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
spec:
  storageClassName: civviebot-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  type: local