name: Build and Deploy to GKE

on:
  push:
    branches: [ "dev" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: northamerica-northeast1
  GKE_CLUSTER: civviebot-cluster
  GKE_ZONE: northamerica-northeast1
  DEPLOYMENT_NAME: civviebot-image
  REPOSITORY: civviebot-builds
  IMAGE: static-site
  CIVVIEBOT_DB_DIALECT: ${{ secrets.CIVVIEBOT_DB_DIALECT }}
  CIVVIEBOT_DB_DRIVER: ${{ secrets.CIVVIEBOT_DB_DRIVER }}
  CIVVIEBOT_DB_URL_USERNAME: ${{ secrets.CIVVIEBOT_DB_URL_USERNAME }}
  CIVVIEBOT_DB_URL_PASSWORD: ${{ secrets.CIVVIEBOT_DB_URL_PASSWORD }}
  CIVVIEBOT_DB_URL_DATABASE: ${{ secrets.CIVVIEBOT_DB_URL_DATABASE }}
  CIVVIEBOT_DB_URL_HOST: ${{ secrets.CIVVIEBOT_DB_URL_HOST }}
  CIVVIEBOT_DB_URL_PORT: ${{ secrets.CIVVIEBOT_DB_URL_PORT }}
  DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: 'projects/516245687605/locations/global/workloadIdentityPools/civviebot/providers/civviebot-provider'
